application:
  deviceserver:
    version: 1.0.0
    httpserver:
      host: 0.0.0.0
      port: 8081
      mode: dev
      readtimeout: 5
      writetimeout: 5
  authserver:
    version: 1.0.0
      httpserver:
        host: 0.0.0.0
        port: 8081
        mode: dev
        readtimeout: 5
        writetimeout: 5
    jwtkey: kvkvkvkvkv
    tokentimeout: 60
datasource:
  type: mysql
  host: 127.0.0.1
  port: 3306
  username: root
  password: admin
  dbname:
