application:
  deviceserver:
    version: 1.0.0
    httpserver:
      host: 0.0.0.0
      port: 8100
      mode: dev
      readtimeout: 5
      writetimeout: 5
  authserver:
    version: 1.0.0
    httpserver:
      host: 0.0.0.0
      port: 8101
      mode: dev
      readtimeout: 5
      writetimeout: 5
    jwtkey: kvkvkvkvkv
    tokentimeout: 60
datasource:
  mysql:
    url: 172.31.45.151:3306
    username: admin
    password: admin
    dbname: kv-iot
